spring:
  application:
    name: spring-cloud-demo-producter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true    # 访问路径显示IP地址