server:
    port: 8761
    servlet:
        context-path: /
spring:
    application:
        name: eureka-server
    freemarker:
        prefer-file-system-access: false
eureka:
    instance:
        hostname: localhost
    client:
        fetch-registry: false
        register-with-eureka: false
        service-url:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
