server:
    port: 7001
spring:
    application:
        name: eureka-server-${server.port}
    freemarker:
        prefer-file-system-access: false
eureka:
    instance:
        hostname: ${spring.application.name}
    client:
        #        fetch-registry: false
        #        register-with-eureka: false
        service-url:
            defaultZone: http://localhost:7002/eureka
