server:
  port: 7001
spring:
  application:
    name: eureka-server
  freemarker:
    prefer-file-system-access: false
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    hostname: eureka-01.com
  client:
    #        fetch-registry: false
    #        register-with-eureka: false
    service-url:
      defaultZone: http://eureka-02.com:7002/eureka/
